version: '3.8'

services:
  inference-center:
    build: .
    container_name: inference-center
    # IMPORTANTE: Habilitar acceso a la GPU NVIDIA
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - "8001:8001"
    volumes:
      # Montar la carpeta de logs
      - ./logs:/app/logs
      # Montar la carpeta de modelos del host
      - /home/sito/jota-db/models:/home/sito/jota-db/models
      # Montar la configuración de entorno
      - ./.env:/app/.env
    environment:
      - MODELS_PATH=/home/sito/jota-db/models
      - PORT=8001
    env_file:
      - .env
    restart: unless-stopped
